// Generated by gencpp from file ros_service_assignment/rectangle_area.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREA_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREA_H

#include <ros/service_traits.h>


#include <ros_service_assignment/rectangle_areaRequest.h>
#include <ros_service_assignment/rectangle_areaResponse.h>


namespace ros_service_assignment
{

struct rectangle_area
{

typedef rectangle_areaRequest Request;
typedef rectangle_areaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rectangle_area
} // namespace ros_service_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_service_assignment::rectangle_area > {
  static const char* value()
  {
    return "8c40727d6328d1ee6f8baf8490116346";
  }

  static const char* value(const ::ros_service_assignment::rectangle_area&) { return value(); }
};

template<>
struct DataType< ::ros_service_assignment::rectangle_area > {
  static const char* value()
  {
    return "ros_service_assignment/rectangle_area";
  }

  static const char* value(const ::ros_service_assignment::rectangle_area&) { return value(); }
};


// service_traits::MD5Sum< ::ros_service_assignment::rectangle_areaRequest> should match
// service_traits::MD5Sum< ::ros_service_assignment::rectangle_area >
template<>
struct MD5Sum< ::ros_service_assignment::rectangle_areaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::rectangle_area >::value();
  }
  static const char* value(const ::ros_service_assignment::rectangle_areaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::rectangle_areaRequest> should match
// service_traits::DataType< ::ros_service_assignment::rectangle_area >
template<>
struct DataType< ::ros_service_assignment::rectangle_areaRequest>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::rectangle_area >::value();
  }
  static const char* value(const ::ros_service_assignment::rectangle_areaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_service_assignment::rectangle_areaResponse> should match
// service_traits::MD5Sum< ::ros_service_assignment::rectangle_area >
template<>
struct MD5Sum< ::ros_service_assignment::rectangle_areaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::rectangle_area >::value();
  }
  static const char* value(const ::ros_service_assignment::rectangle_areaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::rectangle_areaResponse> should match
// service_traits::DataType< ::ros_service_assignment::rectangle_area >
template<>
struct DataType< ::ros_service_assignment::rectangle_areaResponse>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::rectangle_area >::value();
  }
  static const char* value(const ::ros_service_assignment::rectangle_areaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREA_H
