// Generated by gencpp from file ros_service_assignment/rectangle_areaResponse.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREARESPONSE_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service_assignment
{
template <class ContainerAllocator>
struct rectangle_areaResponse_
{
  typedef rectangle_areaResponse_<ContainerAllocator> Type;

  rectangle_areaResponse_()
    : area(0.0)  {
    }
  rectangle_areaResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef float _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rectangle_areaResponse_

typedef ::ros_service_assignment::rectangle_areaResponse_<std::allocator<void> > rectangle_areaResponse;

typedef boost::shared_ptr< ::ros_service_assignment::rectangle_areaResponse > rectangle_areaResponsePtr;
typedef boost::shared_ptr< ::ros_service_assignment::rectangle_areaResponse const> rectangle_areaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator1> & lhs, const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator1> & lhs, const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_service_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba46cd039de682077b3eaa09c3500c5c";
  }

  static const char* value(const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba46cd039de68207ULL;
  static const uint64_t static_value2 = 0x7b3eaa09c3500c5cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service_assignment/rectangle_areaResponse";
  }

  static const char* value(const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 area\n"
;
  }

  static const char* value(const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rectangle_areaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service_assignment::rectangle_areaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLE_AREARESPONSE_H
